$(document).ready(function(){
  $('buttton#dropbtn1').click(function(){
    $("button#dropdown2").show();
    $("button#dropdown2").hide();
  });
  $('#dropbtn1').click(function(){
    $("buttton#dropdown2").show();
    $("button#dropdown2").hide();
  });
});
$(document).ready(function(){
  $("#hide").click(function(){
    $("button#haha").hide();
  });
   $("#hide").click(function(){
    $("button#haha").show();
});

});
